

grammar_words = [
    "ich", "du", "er", "sie", "es", "wir", "ihr", "Sie", "mir", "dir", 
    "mich", "dich", "ihn", "uns", "euch", "ihnen", "meine", "deine", 
    "sein", "ihr", "unser", "euer", "mein", "dein", "seine", "ihre", 
    "das", "der", "die", "ein", "eine", "einen", "einem", "einer", 
    "des", "dem", "den", "im", "am", "vom", "zum", "zur", "war", 
    "ist", "sind", "bin", "bist", "warst", "waren", "hat", "habe", 
    "hatte", "haben", "sein", "wird", "werden", "wurde", "kann", 
    "können", "konnte", "will", "wollen", "muss", "müssen", 
    "dürfen", "soll", "sollen", "möchte", "hätte", "wäre", "von", 
    "bis", "zu"
]

variations = {
    "ich": ["mir", "mich", "mein"],
    "du": ["dir", "dich", "dein"],
    "er": ["ihn", "sein", "er"],
    "sie": ["ihre", "sie", "ihr"],
    "es": ["sein", "ich", "du"],
    "wir": ["uns", "wir", "unser"],
    "ihr": ["euch", "ihr", "euer"],
    "Sie": ["Ihr", "Sie", "Sie"],
    "mir": ["mich", "mein", "mir"],
    "dir": ["dich", "dein", "dir"],
    "mich": ["mir", "mein", "mich"],
    "dich": ["dir", "dein", "dich"],
    "ihn": ["ihm", "sein", "ihn"],
    "uns": ["wir", "uns", "unser"],
    "euch": ["ihr", "euch", "euer"],
    "ihnen": ["ihm", "sie", "ihnen"],
    "meine": ["mein", "meine", "mein"],
    "deine": ["dein", "deine", "dein"],
    "sein": ["sein", "seine", "ihm"],
    "ihr": ["ihre", "ihr", "ihren"],
    "unser": ["uns", "unser", "unsere"],
    "euer": ["euer", "eure", "dein"],
    "mein": ["meine", "mein", "mein"],
    "dein": ["deine", "dein", "dein"],
    "seine": ["sein", "ihn", "seinen"],
    "ihre": ["ihr", "ihre", "ihren"],
    "das": ["dies", "jenes", "dieses"],
    "der": ["die", "das", "der"],
    "die": ["der", "das", "die"],
    "ein": ["eine", "einem", "einer"],
    "eine": ["ein", "einen", "einer"],
    "einen": ["ein", "eine", "einem"],
    "einem": ["ein", "einen", "eine"],
    "einer": ["ein", "eine", "einen"],
    "des": ["dem", "der", "des"],
    "dem": ["des", "der", "dem"],
    "den": ["die", "dem", "den"],
    "im": ["am", "vom", "im"],
    "am": ["im", "vom", "am"],
    "vom": ["im", "am", "vom"],
    "zum": ["zu", "zu dem", "zum"],
    "zur": ["zu der", "zur", "zur"],
    "war": ["warst", "waren", "wird"],
    "ist": ["war", "wird", "sind"],
    "sind": ["sind", "sind", "waren"],
    "bin": ["bist", "war", "bin"],
    "bist": ["bin", "warst", "bist"],
    "warst": ["war", "bist", "waren"],
    "waren": ["war", "sind", "waren"],
    "hat": ["habe", "hatte", "haben"],
    "habe": ["hat", "hatte", "haben"],
    "hatte": ["hat", "habe", "hatte"],
    "haben": ["hat", "habe", "haben"],
    "sein": ["war", "wird", "werden"],
    "wird": ["wurde", "wird", "wird"],
    "werden": ["wurde", "werden", "werden"],
    "wurde": ["wird", "werden", "wurde"],
    "kann": ["konnte", "konnte", "kann"],
    "können": ["konnte", "könnte", "könnten"],
    "konnte": ["konnte", "konnte", "konnte"],
    "will": ["wollen", "möchte", "will"],
    "wollen": ["will", "wollen", "wollte"],
    "muss": ["müssen", "müsste", "muss"],
    "müssen": ["muss", "müsste", "müssen"],
    "dürfen": ["dürfte", "dürfen", "dürften"],
    "soll": ["sollte", "sollen", "soll"],
    "sollen": ["soll", "sollte", "sollen"],
    "möchte": ["möchten", "möchte", "möchtest"],
    "hätte": ["hätte", "haben", "wäre"],
    "wäre": ["wird", "wäre", "wären"],
    "von": ["aus", "von", "über"],
    "bis": ["nach", "bis", "zu"],
    "zu": ["von", "zu", "für"]
}

topics = {
    'primary_school': [
        "Introducing myself",
        "Describing my family",
        "Talking about my favorite food",
        "Explaining my daily routine",
        "Describing my school subjects",
        "Talking about my school friends",
        "What I like to do in my free time",
        "Explaining the weather",
        "Describing my house",
        "Talking about my pets",
        "Discussing my hobbies",
        "Telling a short story",
        "Talking about my birthday celebrations",
        "Describing my classroom",
        "Explaining what I want to be when I grow up",
        "What I do during school holidays",
        "Discussing my favorite game",
        "Talking about sports I like to play",
        "Describing a typical day at school",
        "Discussing school subjects",
        "Talking about my best friend",
        "Explaining what I want to learn next in school",
        "Discussing what I enjoy about school",
        "Talking about school projects",
        "Describing my favorite teacher",
        "Talking about a day trip or excursion",
        "Discussing the books I read",
        "Talking about the seasons and what I do in each",
        "Describing the toys I loved as a child",
        "Explaining my favorite TV shows",
        "Describing a family celebration",
        "Talking about holidays and traditions",
        "Explaining my favorite foods and snacks",
        "Describing a typical school lunch",
        "Talking about my favorite subject",
        "Explaining my experience with a school project",
        "Talking about my favorite movie",
        "Describing my dream vacation",
        "Explaining the rules of a game",
        "Describing a famous landmark",
        "Talking about a typical school day",
        "Describing a trip to the zoo or museum",
        "Talking about how I prepare for school tests",
        "Describing what I like to do during recess",
        "Talking about my favorite sports team",
        "Describing my favorite song",
        "Talking about my favorite holiday destination",
        "Talking about a visit to a park",
        "Discussing my experience with learning a new language",
        "Talking about a historical figure I learned about in school",
        "Describing the local library",
        "Talking about how I celebrate Christmas",
    ],

    'high_school': [
        "Talking about my favorite high school subject",
        "Describing my high school timetable",
        "Explaining my study routine",
        "Talking about my high school friends",
        "Discussing the challenges of high school life",
        "Explaining what I want to be when I graduate",
        "Talking about my high school exams",
        "Discussing my high school projects and assignments",
        "Talking about my hobbies and how I spend my free time",
        "Describing a weekend with friends",
        "Talking about extracurricular activities in high school",
        "Explaining how I prepare for an important exam",
        "Talking about a field trip or excursion",
        "Describing my high school classroom",
        "Explaining how I travel to school every day",
        "Describing the subjects I’m learning this year",
        "Talking about my favorite teacher",
        "Talking about high school sports and competitions",
        "Explaining my plans for the summer holidays",
        "Talking about my favorite sport and team",
        "Describing my ideal future job",
        "Talking about a high school project",
        "Discussing what I’ve learned in my history class",
        "Talking about a student exchange program",
        "Explaining a typical school day",
        "Talking about high school in my country vs others",
        "Describing the local high school in my city",
        "Discussing how students celebrate graduation",
        "Talking about university options for the future",
        "Describing how students use technology in schools",
        "Talking about my favorite high school event",
        "Explaining the difference between public and private schools",
        "Discussing school clubs and societies",
        "Talking about school dances and social events",
        "Describing my experience learning a new language",
        "Explaining the importance of good study habits",
        "Talking about how I handle school stress",
        "Describing the school library and its resources",
        "Talking about student rights",
        "Discussing the importance of studying a second language",
        "Describing a favorite high school memory",
        "Talking about volunteering opportunities at school",
        "Discussing the importance of physical education",
        "Talking about the subjects I want to focus on in university",
        "Explaining what I want to study at university",
        "Discussing high school exams",
        "Talking about my ideal university",
        "Explaining a school exchange program",
        "Describing a typical student",
        "Talking about my favorite school trip",
        "Discussing the advantages of bilingual education",
        "Explaining how schools prepare students for the future",
    ],

    'university': [
        "Describing my university campus",
        "Explaining the subjects I’m studying",
        "Talking about university life",
        "Describing my university dorm or apartment",
        "Talking about my professors and lectures",
        "Discussing university exams and grading systems",
        "Talking about student discounts and benefits",
        "Describing university clubs and organizations",
        "Explaining my favorite university course",
        "Talking about my future career goals",
        "Discussing the importance of networking in university",
        "Describing a typical university day",
        "Talking about student life outside the university",
        "Explaining the university timetable",
        "Discussing university tuition fees",
        "Talking about student exchange programs",
        "Describing how students prepare for final exams",
        "Talking about university libraries and study spaces",
        "Explaining the importance of research in university",
        "Talking about university internship opportunities",
        "Discussing how to balance study and social life",
        "Talking about university group projects",
        "Describing my university’s international students",
        "Talking about the challenges of living in a foreign country",
        "Explaining how to get a part-time job as a student",
        "Discussing the benefits of learning a second language",
        "Talking about my university's campus events",
        "Describing my academic achievements in university",
        "Talking about university graduation and its significance",
        "Describing student life in a foreign country",
        "Explaining how university courses are structured",
        "Talking about the importance of internships",
        "Discussing how to improve study skills",
        "Talking about the benefits of studying abroad",
        "Describing the university cafeteria",
        "Talking about university sports and fitness options",
        "Explaining what I want to do after university",
        "Describing my university professors' teaching style",
        "Discussing the importance of time management in university",
        "Talking about university networking events",
        "Describing a recent university exam",
        "Explaining how I manage university stress",
        "Talking about my experience with university projects",
        "Describing the university’s student services",
        "Talking about what I’ve learned in university so far",
        "Describing a university seminar I attended",
        "Explaining the university application process",
    ],

    'office_job': [
        "Describing a typical workday",
        "Talking about my job responsibilities",
        "Explaining the tasks I do in my office",
        "Discussing my colleagues and their roles",
        "Talking about the importance of teamwork",
        "Describing my office workspace",
        "Explaining how I communicate with my team",
        "Discussing my work schedule",
        "Talking about meetings and presentations",
        "Describing the tools I use in my job",
        "Talking about professional skills I’m developing",
        "Explaining the office culture",
        "Describing how I organize my work tasks",
        "Talking about work-related challenges",
        "Describing a project I’m working on",
        "Talking about my company’s mission",
        "Discussing work-life balance",
        "Talking about office events or celebrations",
        "Explaining the role of technology in my job",
        "Describing how I prepare for a work meeting",
        "Talking about customer service in my job",
        "Explaining my career goals",
        "Describing my work relationships",
        "Talking about job promotions",
        "Discussing the importance of professional development",
        "Talking about office communication tools",
        "Explaining office etiquette",
        "Talking about work-related travel",
        "Describing the company where I work",
        "Talking about my manager's role",
        "Explaining office policies",
        "Talking about my job interview experience",
        "Describing my morning routine before work",
        "Discussing how I handle office stress",
        "Talking about company projects",
        "Describing the role of HR in the company",
        "Talking about office deadlines",
        "Discussing career advancement opportunities",
        "Explaining the importance of networking",
        "Talking about work meetings and their importance",
        "Describing office productivity tools",
        "Talking about my favorite part of the job",
        "Discussing professional achievements",
        "Talking about the company’s work environment",
        "Explaining how I collaborate with coworkers",
        "Talking about office goals and performance",
        "Describing a typical workweek",
        "Talking about workplace challenges and solutions",
        "Describing the career path I hope to follow",
        "Talking about office teamwork activities",
    ],

    'travel': [
        "Describing your favorite city in Germany to visit",
        "Talking about the best way to travel around Germany",
        "Explaining the German public transport system",
        "Describing a visit to Berlin's Brandenburg Gate",
        "Talking about a trip to the Black Forest",
        "Explaining how to order food in a German restaurant",
        "Describing a visit to Neuschwanstein Castle",
        "Talking about the famous German beer gardens",
        "Describing a trip to the Bavarian Alps",
        "Talking about a cultural festival in Germany",
        "Explaining the German train system (Deutsche Bahn)",
        "Talking about the best time to visit Germany",
        "Describing a road trip through Germany's Romantic Road",
        "Explaining how to visit the Rhine Valley castles",
        "Talking about traveling in Germany during Oktoberfest",
        "Describing a visit to the famous Cologne Cathedral",
        "Talking about visiting museums in Berlin",
        "Explaining how to get around in a German city",
        "Talking about Germany’s most famous landmarks",
        "Describing the best cities to visit in Germany for tourists",
        "Talking about German Christmas markets",
        "Explaining how to find a good hotel in Germany",
        "Describing the food you can try while traveling in Germany",
        "Talking about a trip to the German seaside (Baltic and North Sea)",
        "Explaining how to visit a German castle",
        "Describing the cultural differences you experience while traveling in Germany",
        "Talking about biking through the German countryside",
        "Explaining the significance of German hiking trails",
        "Describing your experience at a German spa or wellness center",
        "Talking about exploring the medieval town of Rothenburg ob der Tauber",
        "Describing the local transportation in Munich",
        "Explaining how to visit the Oktoberfest in Munich",
        "Talking about the best places to visit in Hamburg",
        "Describing a visit to the Zugspitze mountain",
        "Talking about the best museums in Germany",
        "Explaining how to travel to Germany's neighboring countries",
        "Describing the experience of staying at a German guesthouse (Gasthof)",
        "Talking about the significance of German castles and their history",
        "Describing the German Autobahn and driving in Germany",
        "Talking about the most popular German souvenirs to buy",
        "Describing the natural beauty of Germany’s national parks",
        "Explaining the importance of German beer in the culture",
        "Talking about visiting the UNESCO World Heritage sites in Germany",
        "Describing a visit to the German city of Dresden",
        "Talking about the wine regions in Germany, such as the Moselle Valley",
        "Describing the architecture of German cities like Frankfurt or Stuttgart",
        "Talking about the experience of eating traditional German street food",
        "Describing your experience at a German Christmas market in Nuremberg",
        "Talking about the different regional cuisines you can try in Germany",
        "Describing the unique towns in Germany such as Bamberg or Heidelberg",
        "Talking about the best shopping districts in Germany’s major cities",
        "Explaining how to visit the famous German palaces like Sanssouci",
        "Describing your experience at the Berlin Wall Memorial",
        "Talking about the beautiful lake districts in Germany like Lake Constance",
        "Describing your trip to the city of Leipzig and its cultural significance",
        "Talking about how to explore German folklore and traditions",
    ],

    'just_curious': [
        "Explaining the concept of time in different cultures",
        "Talking about how languages evolve over time",
        "Discussing the importance of learning a second language",
        "Describing the role of dreams in different cultures",
        "Talking about unique traditions in various cultures",
        "Explaining the history behind a popular holiday",
        "Discussing how people in different countries greet each other",
        "Talking about the differences between urban and rural life",
        "Describing how technology affects our daily lives",
        "Talking about how humans communicate non-verbally",
        "Explaining how music is created and its impact on culture",
        "Discussing famous historical events and their significance",
        "Talking about the meaning of art in various cultures",
        "Explaining the origins of certain customs or practices",
        "Talking about space exploration and its possibilities",
        "Discussing the role of social media in modern society",
        "Talking about famous inventions and their impact on society",
        "Explaining the importance of preserving historical landmarks",
        "Talking about human rights and their global implications",
        "Discussing how people from different countries celebrate the New Year",
        "Explaining how holidays are celebrated in different countries",
        "Talking about the concept of fairness and justice across cultures",
        "Describing how the internet has changed communication",
        "Talking about different methods of education around the world",
        "Discussing the significance of different colors in various cultures",
        "Talking about famous discoveries that changed the world",
        "Explaining the concept of sustainable living",
        "Talking about the influence of food culture on global society",
        "Describing the process of making traditional clothing",
        "Talking about famous landmarks and their historical context",
        "Explaining the concept of equality and gender roles",
        "Discussing why people travel for leisure or business",
        "Talking about the role of animals in various cultures",
        "Describing the concept of time management",
        "Talking about what makes a great leader",
        "Explaining the meaning of different gestures around the world",
        "Talking about how different countries view beauty and fashion",
        "Discussing the importance of mental health in modern life",
        "Explaining the relationship between humans and the environment",
        "Talking about the process of making and appreciating art",
        "Explaining how sports play a role in society",
        "Talking about the influence of literature on culture",
        "Explaining the process of historical research",
        "Talking about the difference between right and wrong across cultures",
        "Describing the significance of national symbols",
        "Discussing the importance of family and social bonds",
        "Talking about the role of food in social gatherings",
        "Explaining how people adapt to different environments",
        "Talking about the human desire for exploration and discovery",
        "Discussing the concept of hospitality in different cultures",
        "Talking about the role of technology in solving global issues",
        "Explaining how folklore and myths shape societies",
        "Discussing the role of philosophy in different cultures",
    ]
}

common_nouns = [
    'Apfel', 'Hund', 'Haus', 'Baum', 'Auto', 'Buch', 'Stuhl', 'Computer', 'Stadt'
]